# Generated by Django 4.1.1 on 2022-09-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Порядковый номер заказа",
                    ),
                ),
                (
                    "order_id",
                    models.IntegerField(unique=True, verbose_name="ID заказа"),
                ),
                ("price_usd", models.FloatField(verbose_name="Стоимость в $")),
                (
                    "price_rub",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Стоимость в рублях"
                    ),
                ),
                ("delivery_date", models.DateField(verbose_name="Срок поставки")),
            ],
        ),
    ]
