# Generated by Django 4.1.1 on 2022-09-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price_rub",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Стоимость в рублях",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="price_usd",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Стоимость в $"
            ),
        ),
    ]
